theme: "jekyll-theme-midnight"
title: "Bitterbrook Cryptozoological Society"
description: "See something you couldn't explain in our mountain woods? Afraid no one will believe you? Contact us! Bitterbrook Cryptozoological Society (BCS) is an amateur cryptozoology/urban legend group collecting and archiving evidence of our strange little town!"

