theme: "jekyll-theme-midnight"
title: "Welcome to The Bitterbrook Unseen World's Explorer!"
description: "See something you couldn't explain in our mountain woods? Afraid no one will believe you? Contact us! The Unseen World's Explorer is an amateur cryptozoology/urban legend group collecting and archiving evidence of our strange little town!"
